
// This file is automatically generated. Do not edit it directly.
import { supabase as appSupabase } from '@/lib/supabase';

// Re-export the app's supabase client to ensure we use a single instance
export const supabase = appSupabase;

// For typing purposes
import type { Database } from './types';
